name: delete-tweets

on:
  schedule:
    - cron: '0 15 * * *' # UTC0時

jobs:
  delete-tweets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npm run start
